"""add_metrics_columns_to_training_plan

Revision ID: b35ed45b716e
Revises: b516ba1cdb04
Create Date: 2026-06-03 17:15:14.359159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35ed45b716e'
down_revision: Union[str, Sequence[str], None] = 'b516ba1cdb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('training_plans', sa.Column('trimp', sa.Float(), nullable=True))
    op.add_column('training_plans', sa.Column('target_hr_zone', sa.String(length=50), nullable=True))
    op.add_column('training_plans', sa.Column('predicted_weight', sa.Float(), nullable=True))
    op.alter_column('training_plans', 'workout_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_plans', 'workout_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('training_plans', 'predicted_weight')
    op.drop_column('training_plans', 'target_hr_zone')
    op.drop_column('training_plans', 'trimp')
    op.drop_column('training_plans', 'calories')
    # ### end Alembic commands ###
